import { describe, expect, it, vi } from "vitest";

import { createModelServiceClient } from "../src/services/ai/modelServiceClient.js";

const requestId = "11111111-1111-4111-8111-111111111111";
const opportunity = {
  opportunityId: "10000000-0000-4000-8000-000000000001",
  title: "Fictional Climate Fellowship", organization: "Example Foundation", type: "fellowship",
  description: "A fictional programme for testing.", requirements: ["JavaScript experience"],
  eligibility: ["educationLevels: undergraduate"], benefits: ["Mentorship"], countryCodes: ["KE"],
  isGlobal: false, location: "Nairobi, Kenya", locationMode: "hybrid",
  deadline: "2027-01-01T00:00:00.000Z",
};
const server = {
  schemaVersion: "1.0",
  modelMetadata: { provider: "ollama", name: "qwen3:4b-instruct", pretrained: true },
  limitation: "Generated by a small, English-first pretrained language model; human review is required.",
};
const outputs = {
  summary: { data: { ...server, overview: "A fictional fellowship.", eligibilityHighlights: [], benefits: ["Mentorship"], deadlineNotes: "Deadline is supplied.", missingInformation: [], disclaimer: "This summary is AI-assisted guidance; verify every detail with the official opportunity source." }, requestId },
  readiness: { data: { ...server, readinessAssessment: "The supplied profile has relevant evidence.", strengths: ["JavaScript is listed."], gaps: [], nextActions: ["Review the official criteria."], disclaimer: "This readiness explanation is guidance, not a guarantee of eligibility, selection, funding, or success." }, requestId },
  cv: { data: { ...server, strengths: ["Lists JavaScript."], relevantEvidence: ["Built a fictional project."], gaps: [], suggestions: ["Add measurable context if truthful."], missingInformation: [], disclaimer: "This CV analysis requires human review and does not guarantee employment or application success." }, requestId },
};
const response = (body, status = 200) => ({ ok: status >= 200 && status < 300, status, json: vi.fn().mockResolvedValue(body) });
const clientFor = (fetchImpl) => createModelServiceClient({
  baseUrl: "http://127.0.0.1:8000", apiKey: "placeholder-key",
  matchingTimeoutMs: 3000, generationTimeoutMs: 75000, fetchImpl,
});

describe("generation model-service client", () => {
  it.each([
    ["summarizeOpportunity", "/v1/generate/opportunity-summary", { opportunity }, outputs.summary],
    ["assessReadiness", "/v1/generate/readiness", { profile: { persona: "student", countryCode: "KE", educationLevel: "undergraduate", fieldOfStudy: "Computer Science", graduationYear: 2027, skills: ["JavaScript"], interests: ["climate"], careerGoals: "Build useful tools." }, opportunity }, outputs.readiness],
    ["analyzeCv", "/v1/generate/cv-analysis", { cvText: "Fictional candidate. Built a class project.", opportunity }, outputs.cv],
  ])("uses one fixed internal request for %s", async (method, path, input, output) => {
    const fetchImpl = vi.fn().mockResolvedValue(response(output));
    await expect(clientFor(fetchImpl)[method]({ input, requestId })).resolves.toEqual(output.data);
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    expect(fetchImpl.mock.calls[0][0]).toBe(`http://127.0.0.1:8000${path}`);
    expect(fetchImpl.mock.calls[0][1].headers).toMatchObject({
      "X-Model-Service-Key": "placeholder-key", "X-Request-Id": requestId,
    });
  });

  it.each([
    [401, "AI_SERVICE_UNAVAILABLE", 503],
    [502, "AI_MALFORMED_RESPONSE", 502],
    [503, "AI_SERVICE_UNAVAILABLE", 503],
    [504, "AI_TIMEOUT", 504],
  ])("sanitizes upstream status %s", async (status, code, statusCode) => {
    const fetchImpl = vi.fn().mockResolvedValue(response({ private: "upstream content" }, status));
    await expect(clientFor(fetchImpl).summarizeOpportunity({ input: { opportunity }, requestId }))
      .rejects.toMatchObject({ code, statusCode });
    expect(fetchImpl).toHaveBeenCalledTimes(1);
  });

  it("maps only a sanitized model refusal and never retries", async () => {
    const fetchImpl = vi.fn().mockResolvedValue(response({ error: { code: "MODEL_REFUSAL", message: "private", requestId } }, 422));
    await expect(clientFor(fetchImpl).summarizeOpportunity({ input: { opportunity }, requestId }))
      .rejects.toMatchObject({ code: "AI_REFUSED", statusCode: 422 });
    expect(fetchImpl).toHaveBeenCalledTimes(1);
  });

  it("rejects invalid JSON, schemas, and mismatched request IDs without retrying", async () => {
    const invalidJson = vi.fn().mockResolvedValue({ ok: true, status: 200, json: vi.fn().mockRejectedValue(new SyntaxError()) });
    await expect(clientFor(invalidJson).summarizeOpportunity({ input: { opportunity }, requestId }))
      .rejects.toMatchObject({ code: "AI_MALFORMED_RESPONSE" });
    const invalidSchema = vi.fn().mockResolvedValue(response({ ...outputs.summary, requestId: "22222222-2222-4222-8222-222222222222" }));
    await expect(clientFor(invalidSchema).summarizeOpportunity({ input: { opportunity }, requestId }))
      .rejects.toMatchObject({ code: "AI_MALFORMED_RESPONSE" });
    expect(invalidJson).toHaveBeenCalledTimes(1);
    expect(invalidSchema).toHaveBeenCalledTimes(1);
  });

  it("uses the generation timeout, supports caller abort, and never logs sensitive content", async () => {
    vi.useFakeTimers();
    const logger = vi.spyOn(console, "error").mockImplementation(() => {});
    const fetchImpl = vi.fn((_url, { signal }) => new Promise((_resolve, reject) => {
      signal.addEventListener("abort", () => reject(Object.assign(new Error("fictional CV private text"), { name: "AbortError" })));
    }));
    const client = createModelServiceClient({ baseUrl: "http://127.0.0.1:8000", apiKey: "private", matchingTimeoutMs: 500, generationTimeoutMs: 10000, fetchImpl });
    const pending = client.analyzeCv({ input: { cvText: "fictional CV private text" }, requestId });
    const assertion = expect(pending).rejects.toMatchObject({ code: "AI_TIMEOUT", statusCode: 504 });
    await vi.advanceTimersByTimeAsync(10000);
    await assertion;
    expect(logger).not.toHaveBeenCalled();
    logger.mockRestore();
    vi.useRealTimers();
  });
});
