insert into public.opportunities (
  id, title, organization, type, description, requirements, eligibility, benefits,
  country_codes, is_global, location, location_mode, deadline, application_url,
  canonical_url, source_name, source_url, status, published_at, last_verified_at
)
values
(
  '10000000-0000-4000-8000-000000000001',
  'UNICEF Internship Programme',
  'UNICEF',
  'internship',
  'UNICEF offers students and recent graduates practical experience through internship vacancies published throughout the year. Individual vacancies define their own functions, locations and closing dates.',
  array['Be at least 18 years old', 'Meet the academic and language requirements published for the selected vacancy'],
  '{"audience":["students","recent graduates"],"availability":"Opportunities are offered throughout the year; each vacancy has its own deadline."}'::jsonb,
  array['Monthly stipend', 'A travel and visa contribution may be available when funding permits', 'Internships normally last 6 to 26 weeks'],
  '{}', true, 'Multiple UNICEF duty stations worldwide', 'unspecified', null,
  'https://jobs.unicef.org/en-us/filter/?search-keyword=&work-type=internship',
  'https://www.unicef.org/careers/internships',
  'UNICEF Careers',
  'https://www.unicef.org/careers/internships',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000002',
  'Knight-Hennessy Scholars 2027 Cohort',
  'Stanford University',
  'scholarship',
  'Knight-Hennessy Scholars supports graduate study at Stanford University and develops a multidisciplinary community of emerging leaders.',
  array['Apply separately to an eligible Stanford graduate degree programme', 'Submit the Knight-Hennessy Scholars application by its published deadline'],
  '{"cohort":2027,"scope":"Applicants from all countries may apply, subject to Stanford graduate programme eligibility."}'::jsonb,
  array['Funding for up to three years of graduate study', 'Leadership development programming', 'Multidisciplinary scholar community'],
  '{}', true, 'Stanford, California, United States', 'onsite', '2026-10-06T20:00:00Z',
  'https://apply.knight-hennessy.stanford.edu/apply/',
  'https://knight-hennessy.stanford.edu/admission',
  'Knight-Hennessy Scholars at Stanford University',
  'https://knight-hennessy.stanford.edu/admission',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000003',
  'Schwarzman Scholars Class of 2027-2028',
  'Schwarzman Scholars',
  'scholarship',
  'Schwarzman Scholars is a one-year master’s programme at Tsinghua University designed to build leadership and deepen understanding between China and the rest of the world.',
  array['Be at least 18 and under 29 on August 1, 2027', 'Complete all undergraduate degree requirements before August 1, 2027', 'Meet the programme English-language requirement'],
  '{"cycle":"U.S./Global","programmeStart":"August 2027","citizenshipNote":"The U.S./Global route is for non-Chinese citizens; separate rules apply to Chinese citizens."}'::jsonb,
  array['Tuition and fees', 'Room and board', 'Travel and study-tour support described by the programme'],
  '{}', true, 'Beijing, China', 'onsite', '2026-09-09T19:00:00Z',
  'https://connect.schwarzmanscholars.org/apply/',
  'https://www.schwarzmanscholars.org/admissions/application-instructions/',
  'Schwarzman Scholars',
  'https://www.schwarzmanscholars.org/admissions/application-instructions/',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000004',
  '2027 Africa Prize for Engineering Innovation',
  'Royal Academy of Engineering',
  'competition',
  'The Africa Prize supports engineering innovators in sub-Saharan Africa through an eight-month commercialisation programme and a competitive prize process.',
  array['The lead applicant must be based in sub-Saharan Africa', 'The innovation must be an engineering solution at an early commercialisation stage', 'Review the official 2027 guidance before applying'],
  '{"region":"sub-Saharan Africa","applicationStage":"Stage 1","officialDeadlineTimezone":"UTC+1"}'::jsonb,
  array['Eight-month training and mentoring programme', 'Access to the Academy network', 'Prize funding described in the official guidance'],
  array['AO','BJ','BW','BF','BI','CV','CM','CF','TD','KM','CD','CG','CI','DJ','GQ','ER','SZ','ET','GA','GM','GH','GN','GW','KE','LS','LR','MG','MW','ML','MR','MU','MZ','NA','NE','NG','RW','ST','SN','SC','SL','SO','ZA','SS','TZ','TG','UG','ZM','ZW'],
  false, 'Sub-Saharan Africa', 'hybrid', '2026-09-08T15:00:00Z',
  'https://grants.raeng.org.uk/',
  'https://africaprize.raeng.org.uk/about-the-prize/how-to-apply/',
  'Royal Academy of Engineering',
  'https://africaprize.raeng.org.uk/about-the-prize/how-to-apply/',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000005',
  'Y Combinator Fall 2026 Batch',
  'Y Combinator',
  'accelerator',
  'Y Combinator is accepting startup applications for its Fall 2026 batch, which runs from October through December in San Francisco.',
  array['Submit a startup application through the official YC application portal', 'Founders should be able to participate in the in-person batch activities described by YC'],
  '{"batch":"Fall 2026","lateApplications":"YC states that late applications may still be considered without a decision-time guarantee."}'::jsonb,
  array['YC investment under its published standard deal', 'Dedicated group-partner support', 'In-person founder programming in San Francisco'],
  '{}', true, 'San Francisco, California, United States', 'onsite', '2026-07-28T03:00:00Z',
  'https://apply.ycombinator.com/',
  'https://www.ycombinator.com/apply',
  'Y Combinator',
  'https://www.ycombinator.com/apply',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000006',
  'The Pollination Project Daily Grants',
  'The Pollination Project',
  'grant',
  'The Pollination Project provides seed funding to grassroots changemakers and considers eligible work from individuals, informal groups and nonprofit organizations around the world.',
  array['The group or organization must have an annual budget below the published limit', 'The project must align with the official funding guidelines', 'Previous recipients and active applicants are subject to the programme restrictions'],
  '{"availability":"Funding decisions are made on a rolling basis.","geography":"Applicants may be based anywhere in the world."}'::jsonb,
  array['Seed funding', 'Connection to a global changemaker community'],
  '{}', true, 'Worldwide', 'remote', null,
  'https://thepollinationproject.smapply.us/',
  'https://thepollinationproject.org/apply/',
  'The Pollination Project',
  'https://thepollinationproject.org/apply/',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000007',
  'Rhodes Global Scholarship 2027',
  'Rhodes Trust',
  'scholarship',
  'The Rhodes Global Scholarship is a fully funded postgraduate award for eligible candidates who are not citizens of an existing Rhodes constituency and who wish to study at the University of Oxford.',
  array['Be ineligible to apply through another Rhodes constituency', 'Have completed or expect to complete an undergraduate degree by July 2027', 'Receive an institutional nomination', 'Meet the requirements of the proposed full-time Oxford course'],
  '{"cohort":2027,"awards":2,"nomination":"A recognised university may nominate up to three Global candidates."}'::jsonb,
  array['Oxford University course fees', 'Living stipend', 'Visa and health-surcharge support described by the Rhodes Trust'],
  '{}', true, 'Oxford, United Kingdom', 'onsite', '2026-07-23T23:59:00Z',
  'https://www.rhodeshouse.ox.ac.uk/scholarships/applications/',
  'https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/',
  'Rhodes Trust',
  'https://www.rhodeshouse.ox.ac.uk/media2/bfygntaa/global_guidance-for-nominating-institutions_2027.pdf',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
),
(
  '10000000-0000-4000-8000-000000000008',
  'World Bank Group Young Professionals Program 2026',
  'World Bank Group',
  'job',
  'The World Bank Group Young Professionals Program recruits early-career professionals across the World Bank, IFC and MIGA for a two-year leadership development programme.',
  array['Hold nationality of a World Bank Group member country', 'Have at least two years of relevant full-time experience after undergraduate study', 'Complete a relevant master’s-level or higher qualification before September 1, 2026', 'Have excellent spoken and written English'],
  '{"applicationWindow":"September 1 through September 30, 2026","experience":"Two to six years in a related work area","programme":"World Bank, IFC and MIGA"}'::jsonb,
  array['Two-year employment programme', 'Leadership and professional development', 'Rotational learning across the World Bank Group'],
  '{}', true, 'Multiple World Bank Group locations', 'unspecified', '2026-09-30T23:59:00Z',
  'https://www.worldbank.org/ext/en/careers/talent-programs/young-professionals-program',
  'https://www.worldbank.org/ext/en/careers/talent-programs/young-professionals-program',
  'World Bank Group Careers',
  'https://www.worldbank.org/ext/en/careers/talent-programs/young-professionals-program',
  'published', '2026-07-17T12:00:00Z', '2026-07-17T12:00:00Z'
);
