import { z } from "zod";

const boundedText = (maximum) => z.string().trim().min(1).max(maximum);
const boundedList = (maximumItems, maximumLength = 300) =>
  z.array(boundedText(maximumLength)).max(maximumItems);

export const MODEL_SERVICE_FEATURES = Object.freeze([
  "combinedText", "profileCountry", "education", "opportunityType", "locationMode",
  "countryEligible", "educationCompatible", "typePreferred", "locationCompatible",
  "skillOverlapCount", "missingRequiredSkillCount",
]);

export const modelServiceRequestSchema = z.object({
  combinedText: boundedText(20_000),
  profileCountry: z.string().regex(/^[A-Z]{2}$/),
  education: z.enum([
    "bachelors_completed", "bachelors_in_progress", "masters_completed",
    "masters_in_progress", "secondary_completed", "secondary_in_progress",
  ]),
  opportunityType: z.enum([
    "accelerator", "competition", "fellowship", "grant", "hackathon",
    "internship", "scholarship", "training",
  ]),
  locationMode: z.enum(["remote", "hybrid", "onsite"]),
  countryEligible: z.boolean(),
  educationCompatible: z.boolean(),
  typePreferred: z.boolean(),
  locationCompatible: z.boolean(),
  skillOverlapCount: z.number().int().min(0).max(100),
  missingRequiredSkillCount: z.number().int().min(0).max(100),
}).strict();

export const modelServiceResponseSchema = z.object({
  data: z.object({
    matchScore: z.number().int().min(0).max(100),
    predictedMatch: z.boolean(),
    probability: z.number().min(0).max(1),
    modelVersion: boundedText(50),
    syntheticBaseline: z.boolean(),
    disclaimer: z.literal("This score is guidance, not a guarantee of eligibility or selection."),
  }).strict(),
  requestId: z.string().uuid(),
}).strict();

const opportunitySchema = z.object({
  opportunityId: z.string().uuid(),
  title: boundedText(180),
  organization: boundedText(180),
  type: z.enum([
    "scholarship", "internship", "job", "grant", "fellowship", "competition",
    "accelerator", "hackathon", "training",
  ]),
  description: boundedText(20_000),
  requirements: boundedList(30, 500),
  eligibility: boundedList(30, 500),
  benefits: boundedList(30, 500),
  countryCodes: z.array(z.string().regex(/^[A-Z]{2}$/)).max(50),
  isGlobal: z.boolean(),
  location: boundedText(180).nullable(),
  locationMode: z.enum(["remote", "hybrid", "onsite", "unspecified"]),
  deadline: z.string().datetime().nullable(),
}).strict();

const profileSchema = z.object({
  persona: z.enum(["student", "recent_graduate", "young_founder"]).nullable(),
  countryCode: z.string().regex(/^[A-Z]{2}$/).nullable(),
  educationLevel: z.enum(["secondary", "undergraduate", "postgraduate", "graduate", "other"]).nullable(),
  fieldOfStudy: boundedText(180).nullable(),
  graduationYear: z.number().int().min(1900).max(2200).nullable(),
  skills: boundedList(50, 80),
  interests: boundedList(50, 80),
  careerGoals: boundedText(2_000).nullable(),
}).strict();

export const opportunitySummaryRequestSchema = z.object({ opportunity: opportunitySchema }).strict();
export const readinessRequestSchema = z.object({ profile: profileSchema, opportunity: opportunitySchema }).strict();
export const cvAnalysisInternalRequestSchema = z.object({
  cvText: boundedText(20_000),
  opportunity: opportunitySchema.optional(),
}).strict();

const modelMetadataSchema = z.object({
  provider: z.literal("ollama"),
  name: boundedText(100),
  pretrained: z.literal(true),
}).strict();
const serverFields = {
  schemaVersion: z.literal("1.0"),
  modelMetadata: modelMetadataSchema,
  limitation: z.literal("Generated by a small, English-first pretrained language model; human review is required."),
};
const cvInputCoverageSchema = z.object({
  mode: z.enum(["full", "representative_excerpt"]),
  originalCharacters: z.number().int().min(1).max(20_000),
  analyzedCharacters: z.number().int().min(1).max(20_000),
}).strict().refine(
  value => value.analyzedCharacters <= value.originalCharacters,
  { message: "Analyzed characters cannot exceed the original input." },
);
const envelope = (data) => z.object({ data, requestId: z.string().uuid() }).strict();

export const opportunitySummaryResponseSchema = envelope(z.object({
  overview: boundedText(1_200),
  eligibilityHighlights: boundedList(10),
  benefits: boundedList(10),
  deadlineNotes: boundedText(500),
  missingInformation: boundedList(10),
  disclaimer: z.literal("This summary is AI-assisted guidance; verify every detail with the official opportunity source."),
  ...serverFields,
}).strict());

export const readinessResponseSchema = envelope(z.object({
  readinessAssessment: boundedText(1_200),
  strengths: boundedList(10),
  gaps: boundedList(10),
  nextActions: boundedList(10),
  disclaimer: z.literal("This readiness explanation is guidance, not a guarantee of eligibility, selection, funding, or success."),
  ...serverFields,
}).strict());

export const cvAnalysisResponseSchema = envelope(z.object({
  strengths: boundedList(12),
  relevantEvidence: boundedList(12),
  gaps: boundedList(12),
  suggestions: boundedList(12),
  missingInformation: boundedList(12),
  inputCoverage: cvInputCoverageSchema,
  disclaimer: z.literal("This CV analysis requires human review and does not guarantee employment or application success."),
  ...serverFields,
}).strict());
