"""Strict contracts for internal Ollama-backed generation features."""

from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, StringConstraints, model_validator
from pydantic_core import PydanticCustomError


SCHEMA_VERSION = "1.0"
PRETRAINED_LIMITATION = (
    "Generated by a small, English-first pretrained language model; human review is required."
)
DISCLAIMERS = {
    "opportunity-summary": "This summary is AI-assisted guidance; verify every detail with the official opportunity source.",
    "readiness": "This readiness explanation is guidance, not a guarantee of eligibility, selection, funding, or success.",
    "cv-analysis": "This CV analysis requires human review and does not guarantee employment or application success.",
    "cover-letter": "This draft requires your review and does not guarantee application success.",
    "essay-assistance": "This assistance must be reviewed in your own voice and does not guarantee selection or funding.",
}


def bounded_text(minimum: int = 1, maximum: int = 2_000):
    return Annotated[
        StrictStr,
        StringConstraints(strip_whitespace=True, min_length=minimum, max_length=maximum),
    ]


ShortText = bounded_text(maximum=300)
MediumText = bounded_text(maximum=1_200)
LongText = bounded_text(maximum=1_500)
InputText = bounded_text(maximum=20_000)
CountryCode = Annotated[
    StrictStr,
    StringConstraints(pattern=r"^[A-Z]{2}$", min_length=2, max_length=2),
]


class StrictSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")


class OpportunityType(str, Enum):
    SCHOLARSHIP = "scholarship"
    INTERNSHIP = "internship"
    JOB = "job"
    GRANT = "grant"
    FELLOWSHIP = "fellowship"
    COMPETITION = "competition"
    ACCELERATOR = "accelerator"
    HACKATHON = "hackathon"
    TRAINING = "training"


class LocationMode(str, Enum):
    ONSITE = "onsite"
    HYBRID = "hybrid"
    REMOTE = "remote"
    UNSPECIFIED = "unspecified"


class EducationLevel(str, Enum):
    SECONDARY = "secondary"
    UNDERGRADUATE = "undergraduate"
    POSTGRADUATE = "postgraduate"
    GRADUATE = "graduate"
    OTHER = "other"


class OpportunityInput(StrictSchema):
    opportunityId: UUID
    title: bounded_text(maximum=180)
    organization: bounded_text(maximum=180)
    type: OpportunityType
    description: InputText
    requirements: list[bounded_text(maximum=500)] = Field(max_length=30)
    eligibility: list[bounded_text(maximum=500)] = Field(max_length=30)
    benefits: list[bounded_text(maximum=500)] = Field(max_length=30)
    countryCodes: list[CountryCode] = Field(max_length=50)
    isGlobal: StrictBool
    location: bounded_text(maximum=180) | None = None
    locationMode: LocationMode
    deadline: datetime | None = None


class ProfileInput(StrictSchema):
    persona: Literal["student", "recent_graduate", "young_founder"] | None = None
    countryCode: CountryCode | None = None
    educationLevel: EducationLevel | None = None
    fieldOfStudy: bounded_text(maximum=180) | None = None
    graduationYear: StrictInt | None = Field(default=None, ge=1900, le=2200)
    skills: list[bounded_text(maximum=80)] = Field(default_factory=list, max_length=50)
    interests: list[bounded_text(maximum=80)] = Field(default_factory=list, max_length=50)
    careerGoals: bounded_text(maximum=2_000) | None = None


class OpportunitySummaryRequest(StrictSchema):
    opportunity: OpportunityInput


class ReadinessRequest(StrictSchema):
    profile: ProfileInput
    opportunity: OpportunityInput


class CvAnalysisRequest(StrictSchema):
    cvText: InputText
    opportunity: OpportunityInput | None = None


class CoverLetterRequest(StrictSchema):
    profile: ProfileInput
    opportunity: OpportunityInput
    tone: Literal["professional", "warm", "concise"] = "professional"
    instructions: bounded_text(maximum=1_000) | None = None


class EssayMode(str, Enum):
    BRAINSTORM = "brainstorm"
    OUTLINE = "outline"
    REVIEW = "review"
    REVISE = "revise"


class EssayAssistanceRequest(StrictSchema):
    mode: EssayMode
    prompt: bounded_text(maximum=3_000)
    draft: InputText | None = None

    @model_validator(mode="after")
    def require_draft_for_review_or_revision(self):
        if self.mode in {EssayMode.REVIEW, EssayMode.REVISE} and self.draft is None:
            raise ValueError("draft is required for review and revise modes")
        return self


OUTCOME_GUARANTEE_PATTERN = re.compile(
    r"\b(?:guaranteed|guarantees|certain to|will (?:be )?"
    r"(?:eligible|selected|accepted|funded|successful)|will receive funding)\b",
    re.IGNORECASE,
)


class SafeModelOutput(StrictSchema):
    @model_validator(mode="after")
    def reject_outcome_guarantees(self):
        def visit(value: object) -> None:
            if isinstance(value, str) and OUTCOME_GUARANTEE_PATTERN.search(value):
                raise PydanticCustomError(
                    "semantic_outcome_guarantee",
                    "outcome guarantees are not allowed",
                )
            if isinstance(value, list):
                for item in value:
                    visit(item)
            elif isinstance(value, dict):
                for item in value.values():
                    visit(item)

        visit(self.model_dump(mode="python"))
        return self


class OpportunitySummaryModelOutput(SafeModelOutput):
    overview: MediumText = Field(description="Short factual overview from the supplied description")
    eligibilityHighlights: list[ShortText] = Field(
        max_length=10, description="Only explicit supplied eligibility facts"
    )
    benefits: list[ShortText] = Field(
        max_length=10, description="Only explicit supplied benefits"
    )
    deadlineNotes: bounded_text(maximum=500) = Field(
        description="Only supplied deadline information"
    )
    missingInformation: list[ShortText] = Field(
        max_length=10, description="Important opportunity facts not supplied"
    )


class ReadinessModelOutput(SafeModelOutput):
    readinessAssessment: MediumText = Field(
        description="Current-state non-numeric explanation with no recommendations or action steps"
    )
    strengths: list[ShortText] = Field(
        max_length=10, description="Capabilities explicitly present in the supplied profile"
    )
    gaps: list[ShortText] = Field(
        max_length=10, description="Explicit requirements unsupported by supplied profile facts"
    )
    nextActions: list[ShortText] = Field(
        max_length=10, description="All recommendations and actions, tied only to explicit requirements or identified gaps"
    )


class CvAnalysisModelOutput(SafeModelOutput):
    strengths: list[ShortText] = Field(
        max_length=12, description="Narrow strengths supported literally by supplied CV text, without generalized proficiency"
    )
    relevantEvidence: list[ShortText] = Field(
        max_length=12, description="Direct evidence stated in supplied CV text"
    )
    gaps: list[ShortText] = Field(
        max_length=12, description="Relevant evidence absent or weak in supplied CV text"
    )
    suggestions: list[ShortText] = Field(
        max_length=12, description="Truthful improvements without invented applicant facts"
    )
    missingInformation: list[ShortText] = Field(
        max_length=12, description="Applicant information that cannot be determined from CV text"
    )


class CoverLetterModelOutput(SafeModelOutput):
    draft: LongText = Field(description="Bounded factual letter using supplied applicant facts only, without unsupported praise or impact")
    assumptions: list[ShortText] = Field(
        max_length=8, description="Cautious framing assumptions, never invented qualifications"
    )
    missingInformation: list[ShortText] = Field(
        max_length=8, description="Facts needed for a stronger letter but not supplied"
    )


class EssayAssistanceModelOutput(SafeModelOutput):
    assistance: LongText = Field(description="Mode-appropriate assistance preserving supplied meaning and voice without inferred events, traits, or outcomes")
    suggestions: list[ShortText] = Field(
        max_length=12, description="Optional improvements based only on supplied content"
    )
    missingInformation: list[ShortText] = Field(
        max_length=12, description="Personal facts or context not supplied"
    )


class RefusalModelOutput(StrictSchema):
    refusal: bounded_text(maximum=1_000)


class ModelMetadata(StrictSchema):
    provider: Literal["ollama"] = "ollama"
    name: bounded_text(maximum=100)
    pretrained: Literal[True] = True


class ServerFields(StrictSchema):
    schemaVersion: Literal[SCHEMA_VERSION] = SCHEMA_VERSION
    disclaimer: bounded_text(maximum=500)
    modelMetadata: ModelMetadata
    limitation: bounded_text(maximum=500) = PRETRAINED_LIMITATION


class OpportunitySummaryData(OpportunitySummaryModelOutput, ServerFields):
    pass


class ReadinessData(ReadinessModelOutput, ServerFields):
    pass


class CvAnalysisData(CvAnalysisModelOutput, ServerFields):
    pass


class CoverLetterData(CoverLetterModelOutput, ServerFields):
    pass


class EssayAssistanceData(EssayAssistanceModelOutput, ServerFields):
    mode: EssayMode


class OpportunitySummaryResponse(StrictSchema):
    data: OpportunitySummaryData
    requestId: bounded_text(maximum=36)


class ReadinessResponse(StrictSchema):
    data: ReadinessData
    requestId: bounded_text(maximum=36)


class CvAnalysisResponse(StrictSchema):
    data: CvAnalysisData
    requestId: bounded_text(maximum=36)


class CoverLetterResponse(StrictSchema):
    data: CoverLetterData
    requestId: bounded_text(maximum=36)


class EssayAssistanceResponse(StrictSchema):
    data: EssayAssistanceData
    requestId: bounded_text(maximum=36)
